{
 "title": "APP Board",
 "time": { "from": "2021-08-26T19:06:21.000Z", "to": "2021-08-26T19:44:20.349Z" },
 "panels": [
  { "title": "App metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App latency",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n)",
     "legendFormat": "0.5:     {{ method }}           {{ uri }}      "
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n)",
     "legendFormat": "0.95:       {{ method }}            {{ uri }}     "
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n) ",
     "legendFormat": "0.99:       {{ method }}            {{ uri }}     "
    },
    {
     "expr": "histogram_quantile(1,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n) ",
     "legendFormat": "Max:       {{ method }}            {{ uri }}     "
    }
   ]
  },
  {
   "title": "App RPS",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "      {{ method }}            {{ uri }}     "
    }
   ]
  },
  {
   "title": "Pods RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"homework-chart\"}) by (pod)",
     "legendFormat": "      {{ pod }}     "
    }
   ]
  },
  {
   "title": "Pods CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container=\"homework-chart\"}[1m])) by (pod)",
     "legendFormat": "'      {{ pod }}     '"
    }
   ]
  },
  {
   "title": "App  Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"[5].+\"}[1m]))/sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path, method) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "       {{ path }}             {{ method }}     "
    }
   ]
  },
  {
   "title": "Latency nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "0.5:       {{ method }}           {{ path }}     "
    },
    {
     "expr": "histogram_quantile(0.9, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "0.9:       {{ method }}             {{ path }}      "
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "0.95:       {{ method }}             {{ path }}      "
    },
    {
     "expr": "histogram_quantile(1, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "Max:       {{ method }}             {{ path }}      "
    }
   ]
  },
  {
   "title": "Error Rate nginx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[5].+\"}[1m])) / sum(rate(nginx_ingress_controller_requests[1m]))"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "DB Open File Description",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"pg-exporter:80\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_conflicts{datname=\"user_info\"}",
     "legendFormat": "      {{ datname }}      `conflicts`"
    }
   ]
  },
  {
   "title": "DB Select data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=\"user_info\"} != 0",
     "legendFormat": "      {{ datname }}     "
    }
   ]
  },
  {
   "title": "DB Delete data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=\"user_info\"} != 0",
     "legendFormat": "      {{ datname }}    "
    }
   ]
  },
  {
   "title": "DB Insert data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"user_info\"} != 0",
     "legendFormat": "      {{ datname }} `}}}    "
    }
   ]
  },
  {
   "title": "DB Update data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=\"user_info\"} != 0",
     "legendFormat": "      {{ datname }}     "
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"user_info\"} !=0",
     "legendFormat": "      {{ state }}    "
    }
   ]
  },
  {
   "title": "DB Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{datname=\"user_info\"}",
     "legendFormat": "      {{ datname }}      commits"
    }
   ]
  }
 ]
}