{
 "title": "My-App_Dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "APPs Memory usage",
   "type": "gauge",
   "description": "Потребляемая оперативная память приложениями",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container=\"hello-chart\"}) by (pod))/(1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API CPU usage",
   "type": "graph",
   "description": "Потребляемая оперативная память приложениями",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"my.*\"}*100) by (pod)"
    }
   ]
  },
  { "title": "System problems", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 } },
  {
   "title": "DB Data metrics",
   "type": "bargauge",
   "description": "Потребляемая оперативная память приложениями",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=~\"myapp\"}[1m])",
     "legendFormat": "Inserted data"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=~\"myapp\"}[1m])",
     "legendFormat": "Updated data"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=~\"myapp\"}[1m])",
     "legendFormat": "Deleted data"
    }
   ]
  },
  {
   "title": "API Latency by Quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(controller_user_requests_seconds_bucket[2m])*1000))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(controller_user_requests_seconds_bucket[2m])*1000))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(controller_user_requests_seconds_bucket[2m])*1000))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le) (rate(controller_user_requests_seconds_bucket[2m])*1000))",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "INGRESS Latency by Quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "API RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_user_requests_seconds_count{}[2m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "INGRESS RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{}[2m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(controller_user_requests_seconds_count{status!=\"200\"}[2m]))"
    }
   ]
  },
  {
   "title": "INGRESS Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count{status!=\"200\"}[2m]))"
    }
   ]
  }
 ]
}