server:
  port: 8000
management:
  port: 8000
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:5432/user_info?currentSchema=public}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123}
  #    url: jdbc:h2:mem:testdb
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password: sa

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.H2Dialect #
    properties:
      hibernate:
        ddl-auto: update
        default_schema: ${DB_SCHEMA:public}
        jdbc.lob.non_contextual_creation: true
        format_sql: true
        show-sql: false