server:
  port: 8000
management:
  security:
    enabled: false
  port: 8000
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    web:
      exposure:
        include: prometheus
      server:
        request:
          autotime:
            percentiles-histogram: true
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
      status:
        order: FATAL,DOWN,OUT_OF_SERVICE,UNKNOWN,OK,UP
  endpoints:
    enabled-by-default: true
    base-path: /
    web:
      exposure:
        include: '*'

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:5432/user_info?currentSchema=public}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123}
  #    url: jdbc:h2:mem:testdb
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password: sa

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.H2Dialect #
    properties:
      hibernate:
        ddl-auto: update
        default_schema: ${DB_SCHEMA:public}
        jdbc.lob.non_contextual_creation: true
        format_sql: true
        show-sql: false