# Default values for homework-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
updateType: RollingUpdate
image:
  repository: nolife1349/homework2:v3

containerPort: 8000
configMapName: app-properties
secret: app-secret
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8000
livenessProbe:
  httpGet:
    path: /health
    port: 8000

service:
  type: NodePort
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  host: arch.homework
  context_path: /otusapp/gorbunovas($|/)(.*)


postgresql:
  enabled: true
  postgresqlUsername: user
  postgresqlPassword: passwd
  postgresqlDatabase: user_info
  postgresqlSchema: public
  service:
    port: "5432"


nginx-ingress:
  controller:
    kind: DaemonSet
    reportNodeInternalIp: true
    daemonset:
      useHostPort: true
      hostPorts:
        http: 80
        https: 443
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

prometheus-operator:
  grafana:
    adminPassword: pwd
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      additionalScrapeConfigs:
        - job_name: pg-exporter
          scrape_interval: 1m
          static_configs:
            - targets: ['pg-exporter:80']


prometheus-postgres-exporter:
  config:
    datasource:
      host: pg-db
      user: user
      password: passwd
      database: user_info