apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  DB_URI: {{ printf "jdbc:postgresql://%s:%s/%s?%s"  (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase .Values.postgresql.postgresqlSchema | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword }}
  DB_SCHEMA: {{ .Values.postgresql.postgresqlSchema }}
