apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "homework-chart.fullname" . }}
  labels:
  {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "homework-chart.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
  {{- include "homework-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: api
      path: /actuator/prometheus
